stages:
  - build
  - push
  - deploy
  - test

variables:
  IMAGE_NAME: localhost:5001/flask-app

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

push:
  stage: push
  script:
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script:
    - docker rm -f flask-app || true
    - docker run -d --name flask-app -p 5000:5000 --restart always $IMAGE_NAME 
test:
  stage: test
  image: curlimages/curl:latest  # Специальный образ с curl
  script:
    - sleep 3  # Wait some before curling
    - curl --fail http://localhost:5000 || (echo "Flask app not responding" && exit 1)
