- name: Ensure .ssh dir exists
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700

- name: Generate SSH key if not present
  openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: ed25519
    comment: "gitlab access"
    force: false
  register: ssh_key

- name: Read public key
  slurp:
    src: "~/.ssh/id_ed25519.pub"
  register: pubkey